packages:
  - "apps/*"
  - "packages/*"
  - "!packages/modules"
  - "packages/modules/*"

onlyBuiltDependencies:
  - esbuild
  - "@prisma/engines"
  - prisma
  - msgpackr-extract
  - sharp
  - unrs-resolver
