export const PAGINATION = {
  NOTICES_LIST_DEFAULT_PAGE_SIZE: 20,
  NOTICES_LIST_MAX_PAGE_SIZE: 50,

  NOTICES_SYNC_DEFAULT_MAX_PAGES: 5,
  NOTICES_SYNC_DEFAULT_PAGE_SIZE: 18,

  PLANNER_DURATION_DEFAULT_LIMIT: 50,
  PLANNER_DURATION_MAX_LIMIT: 200
} as const;

